theme: jekyll-theme-cayman
title: [Chill Development]
description: [Bespoke Software & Web Development company based in Eccles, Manchester]
google_analytics: [UA-110385372-1]
google_analytics_anonymize: false
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      github_hide: true # hides "View on Github"
